# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Math-Symbolic-Custom-Simplification
version:      1.01
version_from: lib/Math/Symbolic/Custom/Simplification.pm
installdirs:  site
requires:
    Math::Symbolic:                0.162
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
